# Generated by Django 2.2 on 2022-09-21 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='municipality',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Municipality'),
        ),
        migrations.AddField(
            model_name='farm',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='farm_base.Owner'),
        ),
        migrations.AddField(
            model_name='farm',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='State'),
        ),
    ]
